from PIL import Image,ImageOps
import os,sys,bitplanelib,math

from shared import *


sprite_names = get_sprite_names()

mirror_sprites = get_mirror_sprites()

# rom copy from 51FB: 4 colors each (with black, only 3 first colors are important!)
fg_weapon_palette_hex = [
     "A8 C0 C7 00 60 00 00 00",  # torch
     "88 66 AA 00 A0 80 C0 00",  # lance, we dumped the tiles when that was active
     "A8 88 AA 00 60 A0 C0 00",  # axe
     "99 AA C0 00 00 C0 00 00",  # shield
     "88 AA C0 00 A0 C0 00 00",  # sword
]
# parse
fg_weapon_palette = [[int(x,16) for x in s.split()] for s in fg_weapon_palette_hex]
# regroup as RGB
fg_weapon_palette = [[((a << 4)+(b>>4)) for a,b in zip(p,p[4:])] for p in fg_weapon_palette]

# game uses dynamic colors to switch between Arthur and the frog. We have color quantize so it's
# more difficult to do that properly, unless... we can find similar colors in existing sprites
# which is the case (giant, plant) so the replacement colors already exist
frog_colors_replacement_dict = {(68,68,102):(102,187,102), (136,136,170):(0,153,0),
   (102,102,136):(0,119,0), (204,0,0):(187,187,187),
   (136,68,0):(170,85,0),(102,0,0):(136,0,0),(204,11,0):(85,85,85)}

ref_fg_weapon_palette = fg_weapon_palette[1]  # lance colors for all weapons

possible_hw_sprites = set()

# uncomment to disable hw sprites completely
#possible_hw_sprites = set()

magenta = (255,0,255)

generated_message = "* generated by convert_graphics.py\n"
dump_it = True

if dump_it:
    if not os.path.exists(dump_dir):
        os.mkdir(dump_dir)
        with open(os.path.join(dump_dir,".gitignore"),"w") as f:
            f.write("*")


def dump_asm_bytes(*args,**kwargs):
    bitplanelib.dump_asm_bytes(*args,**kwargs,mit_format=True)


def ensure_empty(d):
    if d.exists():
        for f in os.listdir(d):
            os.remove(os.path.join(d,f))
    else:
        d.mkdir(parents=True)

def load_tileset(image_name,palette_index,width,height,tileset_name,dumpdir,
dump=False,name_dict=None,cluts=None,tile_number=0,is_bob=False):

##    if isinstance(image_name,str):
##        full_image_path = os.path.join(this_dir,os.path.pardir,"sheets",
##                            tile_type,image_name)
##        tiles_1 = Image.open(full_image_path)
##    else:
    tiles_1 = image_name
    nb_rows = tiles_1.size[1] // height
    nb_cols = tiles_1.size[0] // width


    tileset_1 = []

    if dump:
        dump_subdir = dumpdir / tileset_name
        if palette_index == 0 and tile_number == 0:
            ensure_empty(dump_subdir)

    palette = set()

    for j in range(nb_rows):
        for i in range(nb_cols):

            if cluts is not None and (tile_number not in cluts or palette_index not in cluts[tile_number]):
                # no clut declared for that tile
                tileset_1.append(None)
            else:

                img = Image.new("RGB",(width,height))
                img.paste(tiles_1,(-i*width,-j*height))

                # only consider colors of used tiles
                palette.update(set(bitplanelib.palette_extract(img)))


                tileset_1.append(img)
                # dump tiles
                if not is_bob and dump:
                    img = ImageOps.scale(img,5,resample=Image.Resampling.NEAREST)
                    if name_dict:
                        name = name_dict.get(tile_number,"unknown")
                    else:
                        name = "unknown"

                    img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}.png"))
            tile_number += 1

    if is_bob:

        # rework & dump grouped / non grouped sprites
        # rework tiles which are grouped
        for tile_number,wtile in enumerate(tileset_1):

            if wtile:
                if tile_number in group_sprite_pairs:
                    # change wtile, fetch code +1
                    other_tile_index = tile_number+1
                    other_tile = tileset_1[other_tile_index]
                    if not other_tile:
                        raise Exception(f"pair: other tile index 0x{other_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*2,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(other_tile,(wtile.size[0],0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[other_tile_index] = None  # discatd
                    wtile = new_tile

                elif tile_number in group_sprite_triplets:
                    # change wtile, fetch code +1
                    central_tile_index = tile_number+1
                    central_tile = tileset_1[central_tile_index]
                    right_tile_index = central_tile_index+1
                    right_tile = tileset_1[right_tile_index]
                    if not central_tile:
                        raise Exception(f"triplet: central tile index 0x{central_tile_index:02x} not found")
                    if not right_tile:
                        raise Exception(f"triplet: right tile index 0x{right_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*3,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(central_tile,(wtile.size[0],0))
                    new_tile.paste(right_tile,(wtile.size[0]*2,0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[central_tile_index] = None  # discard
                    tileset_1[right_tile_index] = None  # discard
                    wtile = new_tile

                elif tile_number in group_sprite_quadruplets:
                    # change wtile, fetch code +1
                    central_tile_index = tile_number+1
                    central_tile_1 = tileset_1[central_tile_index]
                    central_tile_2 = tileset_1[central_tile_index+1]
                    right_tile_index = central_tile_index+2
                    right_tile = tileset_1[right_tile_index]
                    if not central_tile_1:
                        raise Exception(f"triplet: central tile index 0x{central_tile_index:02x} not found")
                    if not central_tile_2:
                        raise Exception(f"triplet: central tile index 0x{central_tile_index+1:02x} not found")
                    if not right_tile:
                        raise Exception(f"triplet: right tile index 0x{right_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*4,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(central_tile_1,(wtile.size[0],0))
                    new_tile.paste(central_tile_2,(wtile.size[0]*2,0))
                    new_tile.paste(right_tile,(wtile.size[0]*3,0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[central_tile_index] = None  # discard
                    tileset_1[central_tile_index+1] = None  # discard
                    tileset_1[right_tile_index] = None  # discard
                    wtile = new_tile

            if dump_it and wtile:
                img = ImageOps.scale(wtile,5,resample=Image.Resampling.NEAREST)
                if sprite_names:
                    name = sprite_names.get(tile_number,"unknown")
                else:
                    name = "unknown"

                img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}.png"))



    return sorted(set(palette)),tileset_1

all_tile_cluts = False







sprite_cluts = {}
fg_tile_cluts = {}


read_used_tiles("fg_used_tiles",fg_tile_cluts,FG_NB_TILES,FG_NB_CLUTS)
read_used_tiles("used_sprites",sprite_cluts,SPRITE_NB_TILES,SPRITE_NB_CLUTS)


# now gather all cluts used by letter/digit tiles, logging probably
# missed some
# some tiles are hard to display... We know they are there, we force them
# instead of trying to trigger them by playing to death :)

alphanum_tile_codes = list(range(0,10)) + list(range(ord('A'),ord('Z'))) + list(range(ord('a'),ord('z')))
used_cluts = set()
for atc in alphanum_tile_codes:
    cluts = fg_tile_cluts.get(atc)
    if cluts:
        used_cluts.update(cluts)
# now set cluts for all alphanum tiles
for atc in alphanum_tile_codes:
    fg_tile_cluts[atc] = sorted(used_cluts)

plane_orientations = [("standard",lambda x:x),
("flip",ImageOps.flip),
("mirror",ImageOps.mirror),
("flip_mirror",lambda x:ImageOps.flip(ImageOps.mirror(x)))]

def read_tileset(img_set_list,palette,plane_orientation_flags,cache,is_bob,nb_cluts,next_cache_id = 1):
    nb_planes = int(math.log2(len(palette)))

    tile_table = []
    for n,img_set in enumerate(img_set_list):
        tile_entry = []
        for i,tile in enumerate(img_set):
            entry = dict()
            if tile:

                for b,(plane_name,plane_func) in zip(plane_orientation_flags,plane_orientations):
                    bitplane_sprite_data = None
                    if b:

                        actual_nb_planes = nb_planes

                        # most sprites aren't mirrored. Save a lot of memory!
                        if plane_func == ImageOps.mirror and i not in mirror_sprites:
                            continue

                        wtile = plane_func(tile)

                        if is_bob:
                            actual_nb_planes += 1


                            # only 4 planes + mask => 5 planes
                            orig_wtile = wtile
                            y_start,wtile = bitplanelib.autocrop_y(wtile,mask_color=magenta)
                            height = wtile.size[1]
                            width = wtile.size[0]//8 + 2
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,generate_mask=True,mask_color=magenta)
                            # add sprite data if eligible: player frame, not mirrored

##                            if i in possible_hw_sprites:
##                                # using original, uncropped bitplane data
##                                bitplane_sprite_data = bitplanelib.palette_image2attached_sprites(orig_wtile,None,palette,
##                                sprite_fmode=2,with_control_words=True)
##                                # void the blitter data
##                                bitplane_data = b''
                        else:
                            # 4 planes, no mask
                            height = 8
                            width = 1
                            y_start = 0
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette)

                        plane_size = len(bitplane_data) // actual_nb_planes
                        bitplane_plane_ids = []
                        for j in range(actual_nb_planes):
                            offset = j*plane_size
                            bitplane = bitplane_data[offset:offset+plane_size]

                            cache_id = cache.get(bitplane)
                            if cache_id is not None:
                                bitplane_plane_ids.append(cache_id)
                            else:
                                if any(bitplane):
                                    cache[bitplane] = next_cache_id
                                    bitplane_plane_ids.append(next_cache_id)
                                    next_cache_id += 1
                                else:
                                    bitplane_plane_ids.append(0)  # blank
                        entry[plane_name] = {"width":width,"height":height,"y_start":y_start,"bitplanes":bitplane_plane_ids}
                        if bitplane_sprite_data:
                            entry[plane_name]["sprdat"] = bitplane_sprite_data

            tile_entry.append(entry)

        tile_table.append(tile_entry)

    new_tile_table = [[[] for _ in range(nb_cluts)] for _ in range(len(tile_table[0]))]

    # reorder/transpose. We have 16 * 256 we need 256 * 16
    for i,u in enumerate(tile_table):
        for j,v in enumerate(u):
            new_tile_table[j][i] = v

    return new_tile_table,next_cache_id


def dump_tile_layer(tile_table,prefix,relative_root=None):
    item_decl = "\t.long\t"
    for i,tile_entry in enumerate(tile_table):
        f.write(item_decl)
        if tile_entry and any(tile_entry):
            f.write(f"{prefix}_tile_{i:02x}")
            if relative_root:
                f.write(f"-{relative_root}")
        else:
            f.write("0")
        f.write("\n")

    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            rr = f"{prefix}_tile_{i:02x}"
            f.write(f"{rr}:\n")
            for j,t in enumerate(tile_entry):
                f.write(item_decl)
                if t:
                    f.write(f"{prefix}_tile_{i:02x}_{j:02x}")
                    if relative_root:
                        f.write(f"-{relative_root}")
                else:
                    f.write("0")
                f.write("\n")


    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            for j,t in enumerate(tile_entry):
                if t:
                    name = f"{prefix}_tile_{i:02x}_{j:02x}"

                    f.write(f"{name}:\n")
                    for orientation,_ in plane_orientations:
                        f.write("* orientation={}\n".format(orientation))
                        if orientation in t:
                            data = t[orientation]
                            for bitplane_id in data["bitplanes"]:
                                f.write(item_decl)
                                if bitplane_id:
                                    f.write(f"tile_plane_{bitplane_id:02d}")
                                    if relative_root:
                                        f.write(f"-{relative_root}")
                                else:
                                    f.write("0")
                                f.write("\n")
                            if len(t)==1:
                                # optim: only standard
                                break
                        else:
                            for _ in range(nb_planes):
                                f.write(f"{item_decl}0\n")


def apply_color_replacement(sprite_set_list,quantized):
    """ change colors for list of tilesets (tiles, sprites)
    quantized: RGB => RGB color replacement dictionary
    """

    for sset in sprite_set_list:
        for tile in sset:
            if tile:
                bitplanelib.replace_color_from_dict(tile,quantized)

def quantize_palette(rgb_tuples,img_type,nb_quantize,transparent=None,dump_it=False):
    rgb_configs = set(rgb_tuples)

    nb_target_colors = nb_quantize
    if transparent:
        rgb_configs.remove(transparent)
        # remove black, white, we don't want it quantized
        immutable_colors = (transparent,(0,0,0))
    else:
        immutable_colors = ((0,0,0),)

    for c in immutable_colors:
        rgb_configs.discard(c)
        nb_quantize -= 1

    dump_graphics = False
    # now compose an image with the colors
    clut_img = Image.new("RGB",(len(rgb_configs),1))
    for i,rgb in enumerate(rgb_configs):
        #rgb_value = (rgb[0]<<16)+(rgb[1]<<8)+rgb[2]
        clut_img.putpixel((i,0),rgb)

    reduced_colors_clut_img = clut_img.quantize(colors=nb_quantize,dither=0).convert('RGB')

    # get the reduced palette
    reduced_palette = [reduced_colors_clut_img.getpixel((i,0)) for i,_ in enumerate(rgb_configs)]
    # apply rounding now, else possible color duplicates, which would be a pity
    reduced_palette = bitplanelib.palette_round(reduced_palette,0xF0)

    # now create a dictionary by associating the original & reduced colors
    rval = dict(zip(rgb_configs,reduced_palette))

    # add black & white & transparent back
    for c in immutable_colors:
        rval[c] = c


    if dump_it:  # debug it, create 2 rows, 1 non-quantized, and 1 quantized, separated by bloack
        s = clut_img.size
        ns = (s[0]*30,s[1]*30)
        clut_img = clut_img.resize(ns,resample=0)
        whole_image = Image.new("RGB",(clut_img.size[0],clut_img.size[1]*3))
        whole_image.paste(clut_img,(0,0))
        reduced_colors_clut_img = reduced_colors_clut_img.resize(ns,resample=0)
        whole_image.paste(reduced_colors_clut_img,(0,clut_img.size[1]*2))
        whole_image.save(dump_dir / "{}_colors.png".format(img_type))

    result_nb = len(set(reduced_palette))
    if nb_quantize < result_nb:
        raise Exception(f"quantize: {img_type}: {nb_quantize} expected, found {result_nb}")
    # return it
    return rval



if dump_it:
    if not all_tile_cluts:
        with open(dump_dir / "used_sprites.json","w") as f:
            sprite_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in sprite_cluts.items() if v}
            json.dump(sprite_cluts_dict,f,indent=2)
        with open(dump_dir / "used_fg_tiles.json","w") as f:
            fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
            json.dump(fg_tile_cluts_dict,f,indent=2)





sprite_sheet_dict = {i:Image.open(sheets_path / "sprites" / f"pal_{i:02x}.png") for i in range(SPRITE_NB_CLUTS)}
fg_tile_sheet_dict = {i:Image.open(sheets_path / "fg_tiles" / f"pal_{i:02x}.png") for i in range(FG_NB_CLUTS)}
sprite_sheet_dict = {i:Image.open(sheets_path / "sprites" / f"pal_{i:02x}.png") for i in range(SPRITE_NB_CLUTS)}

###############
# foreground
# not so simple as we need to separate tiles for better colors
###############
fg_tile_upper_palette = set()  # mostly alphanum + title
fg_tile_lower_palette = set()  # frame+weapons+lives
fg_tile_upper_set_list = []
fg_tile_lower_set_list = []

for i,tsd in fg_tile_sheet_dict.items():
    _,tile_set = load_tileset(tsd,i,8,8,"fg_tiles",dump_dir,dump=dump_it,
    cluts=fg_tile_cluts,
    name_dict=None)

    # we need to separate the palettes for OSD because 1) there are too many of them and quantize sucks
    # and 2) the colors of the weapons in the panel is

    upper_tile_set = [None] * len(tile_set)
    lower_tile_set = [None] * len(tile_set)
    for j,tile in enumerate(tile_set):
        tp = set()
        if tile:
            tp = set(bitplanelib.palette_extract(tile))
        if j in lower_osd_tiles:
            fg_tile_lower_palette.update(tp)
            lower_tile_set[j] = tile
        else:
            fg_tile_upper_palette.update(tp)
            upper_tile_set[j] = tile

    fg_tile_upper_set_list.append(upper_tile_set)
    fg_tile_lower_set_list.append(lower_tile_set)

# pad
if len(fg_tile_upper_palette)>16:
    print(f"Too many colors in fg upper tiles ({len(fg_tile_upper_palette)}), quantizing")
    fg_replacement_dict = quantize_palette(fg_tile_upper_palette,"foreground_upper_tiles",16,transparent=None,dump_it=dump_it)
    apply_color_replacement(fg_tile_upper_set_list,fg_replacement_dict)
    fg_tile_upper_palette = sorted(set(fg_replacement_dict.values()))
else:
    fg_tile_upper_palette = sorted(fg_tile_upper_palette)

if len(fg_tile_lower_palette)>16:
    # this is going to be hell to find matching colors for dynamic color changes
    raise Error(f"Too many colors in fg lower tiles ({len(fg_tile_lower_palette)}), quantizing")
##    fg_replacement_dict = quantize_palette(fg_tile_lower_palette,"foreground_lower_tiles",16,transparent=None,dump_it=dump_it)
##    apply_color_replacement(fg_tile_lower_set_list,fg_replacement_dict)
##    fg_tile_lower_palette = sorted(set(fg_replacement_dict.values()))
else:
    # round both palettes & ref palettes to RGB4
    fg_tile_lower_palette_rgb4 = {bitplanelib.rgb4_to_rgb_triplet(bitplanelib.to_rgb4_color(x)) for x in fg_tile_lower_palette}
    ref_fg_weapon_palette_rgb4 = bitplanelib.palette_rgb42palette(ref_fg_weapon_palette)

    # [(128, 128, 160), (96, 96, 128), (160, 160, 192), (0, 0, 0)]
    # non-rounded variants, allowing to find indexes of colors and put them first
    rgb32 = [(136, 136, 170),(102, 102, 136),(170, 170, 204),(0, 0, 0)]

    # place reference colors first: remove them from list to add them later
    for r in rgb32:
        fg_tile_lower_palette.remove(r)

    # sort: zero first, then respect order of original image palette (important!!)
    fg_tile_lower_palette = [(0, 0, 0)] + rgb32[:3] + list(fg_tile_lower_palette)

    if dump_it:
        bitplanelib.palette_dump(fg_tile_lower_palette,dump_dir / "fg_lower_palette.png",bitplanelib.PALETTE_FORMAT_PNG)

print(f"Used fg tile upper colors: {len(fg_tile_upper_palette)}")
print(f"Used fg tile lower colors: {len(fg_tile_lower_palette)}")

# pad to 16 colors
for p in [fg_tile_lower_palette,fg_tile_upper_palette]:
    p += (16-len(p)) * [(0x10,0x20,0x30)]

###############
# background: per level
###############
water_tiles = list(range(0x35B,0x360))
level2_tiles_5to6 = list(range(0x356,0x35B))+list(range(0x10,0x16))+water_tiles

special_fade_palettes = []

context_list = ["level2","level3","level4","level5","level6","level7","map","level1",]
# palette is the same between level 1 and 2 except that
# 1) used tiles are very different, so mixing them would mean quantize & color loss
# 2) we use the steady palette values from level 2 (water is animated by color cycling on level 1, corrupting level 2 ice tower tiles)
for context in context_list:
    bg_tile_sheet_dict = {i:Image.open(sheets_path / "bg_tiles" / context / f"pal_{i:02x}.png") for i in range(BG_NB_CLUTS)}
    bg_tile_cluts = {}
    read_used_tiles(pathlib.Path(context)/"bg_used_tiles",bg_tile_cluts,BG_NB_TILES,BG_NB_CLUTS)

    # stupid cornercase for level 2
    # level starts with ice towers, but palette is then different
    # more annoying: after palette switch, the colors are there they're
    # just in another clut (clut 5 => clut 6) as the water needs displaying afterwards anyway
    # so almost everything can be solved statically by switching the clut index

    if context=="level2":
        for t in level2_tiles_5to6:
            bg_tile_cluts[t]=[6]
        for t in water_tiles:
            bg_tile_cluts[t]=[5,6]

    bg_tile_palette = set()
    bg_tile_set_list = []

    for i,tsd in bg_tile_sheet_dict.items():
        tp,tile_set = load_tileset(tsd,i,16,16,pathlib.Path(context) / "bg_tiles",dump_dir,dump=dump_it,
        cluts=bg_tile_cluts,
        name_dict=None)

        bg_tile_set_list.append(tile_set)
        bg_tile_palette.update(tp)

    if context=="level2":
        # copy some tiles from clut 6 to clut 5 so the colors in ice towers are correct
        tc5 = bg_tile_set_list[5]
        tc6 = bg_tile_set_list[6]
        for t in level2_tiles_5to6:
            tc5[t] = tc6[t]

    if len(bg_tile_palette)>32:
        print(f"{context}: Too many colors in bg tiles ({len(bg_tile_palette)}), quantizing")
        bg_replacement_dict = quantize_palette(bg_tile_palette,"background_tiles",32,transparent=None,dump_it=dump_it)
        bg_tile_palette = sorted(set(bg_replacement_dict.values()))
        apply_color_replacement(bg_tile_set_list,bg_replacement_dict)
    else:
        bg_tile_palette = sorted(bg_tile_palette)

    bg_tile_palette += (32-len(bg_tile_palette)) * [(0x10,0x20,0x30)]
    if context == "level1":
        # generate 3 more palettes for intro fade
        special_fade_palettes = [[tuple(((x*100-(x*i))//100) for x in rgb) for rgb in bg_tile_palette] for i in (10,25,100)]

    print(f"{context}: Used bg tile colors: {len(bg_tile_palette)}")
    if dump_it:
        if not all_tile_cluts:
            with open(dump_dir / "used_sprites.json","w") as f:
                sprite_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in sprite_cluts.items() if v}
                json.dump(sprite_cluts_dict,f,indent=2)
            with open(dump_dir / "used_fg_tiles.json","w") as f:
                fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
                json.dump(fg_tile_cluts_dict,f,indent=2)
            (dump_dir / context).mkdir(exist_ok=True)
            with open(dump_dir / context / "used_bg_tiles.json","w") as f:
                bg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in bg_tile_cluts.items() if v}
                json.dump(bg_tile_cluts_dict,f,indent=2)

    bg_tile_plane_cache = {}
    bg_tile_table,_ = read_tileset(bg_tile_set_list,bg_tile_palette,[True,False,False,False],cache=bg_tile_plane_cache, is_bob=False, nb_cluts=BG_NB_CLUTS)

    map_context = context == "map"

    bank = bg_bank_dir / f"{context}.68k"
    with open(bank,"w") as f:
        f.write("bg_tile_palette:\n")
        bitplanelib.palette_dump(bg_tile_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
        f.write("bg_character_table:\n")
        # map layer is special, included in exe, no need to relocate
        dump_tile_layer(bg_tile_table,"bg",relative_root=None if map_context else "bg_character_table")
        for k,v in bg_tile_plane_cache.items():
            f.write(f"tile_plane_{v:02d}:")
            dump_asm_bytes(k,f)
    banko = bank.parent / f"{bank.stem}.o"

    if not map_context:
        cmd = ["m68k-amigaos-as","-o",banko,bank]
        subprocess.run(cmd,check=True)
        bankbin = data_dir / f"{bank.stem}"
        cmd = ["m68k-amigaos-objcopy","-O","binary",banko,bankbin]
        subprocess.run(cmd,check=True)

###############
# sprites
###############

sprite_palette = set()
sprite_set_list = []

for i,tsd in sprite_sheet_dict.items():
    tp,tile_set = load_tileset(tsd,i,16,16,"sprites",dump_dir,dump=dump_it,
    cluts=sprite_cluts,
    name_dict=get_sprite_names(),
    is_bob=True)
    for j,tile in enumerate(tile_set):
        if tile:
            name = get_sprite_names().get(j)
            if name and name.startswith("frog"):
                bitplanelib.replace_color_from_dict(tile,frog_colors_replacement_dict)
                tile.save(name+f"{j}.png")
    sprite_set_list.append(tile_set)
    sprite_palette.update(tp)

# remove transparent color from palette
sprite_palette.remove(magenta)

if len(sprite_palette)>32:
    print(f"Too many colors in sprite tiles ({len(sprite_palette)}), quantizing")
    # if we specify 32 right away, the algorithm can provide less colors than 32, wasting entries
    # by attempting to quantize with higher values, we guarantee not to waste colors
    for attempt_nb_colors in [35,34,33,32]:
        sprite_replacement_dict = quantize_palette(sprite_palette,"sprite_tiles",attempt_nb_colors,dump_it=dump_it)
        new_sprite_palette = sorted(set(sprite_replacement_dict.values()))
        if len(new_sprite_palette)<=32:
            print(f"Quantization achieved {len(new_sprite_palette)} colors with start colors = {attempt_nb_colors}")
            sprite_palette = new_sprite_palette
            break
    else:
        raise Exception("quantize error")  # not really possible since we try 32 as last chance!

    apply_color_replacement(sprite_set_list,sprite_replacement_dict)
else:
    sprite_palette = sorted(sprite_palette)

sprite_palette += (32-len(sprite_palette)) * [(0x10,0x20,0x30)]



print(f"Used sprite colors: {len(sprite_palette)}")
sprite_palette += (16-len(sprite_palette)) * [(0x10,0x20,0x30)]


# sprite_set_list is now a 16x512 matrix of sprite tiles




empty_32_cols = [(1,1,1)]*len(bg_tile_palette)

tile_plane_cache = {}
bob_plane_cache = {}
fg_tile_upper_table,next_id = read_tileset(fg_tile_upper_set_list,fg_tile_upper_palette,[True,False,False,False],cache=tile_plane_cache, is_bob=False, nb_cluts=FG_NB_CLUTS)
fg_tile_lower_table,_ = read_tileset(fg_tile_lower_set_list,fg_tile_lower_palette,[True,False,False,False],cache=tile_plane_cache, is_bob=False, nb_cluts=FG_NB_CLUTS, next_cache_id = next_id)
sprite_table,_ = read_tileset(sprite_set_list,empty_32_cols+sprite_palette,[True,False,False,False],cache=bob_plane_cache, is_bob=True, nb_cluts=SPRITE_NB_CLUTS)



with open(src_dir / "palette.68k","w") as f:
    f.write(generated_message)
    f.write("fg_tile_upper_palette:\n")
    bitplanelib.palette_dump(fg_tile_upper_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("fg_tile_lower_palette:\n")
    bitplanelib.palette_dump(fg_tile_lower_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("sprite_palette:\n")
    bitplanelib.palette_dump(sprite_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("weapon_palettes:\n")
    for wp in fg_weapon_palette:
        wprgb = bitplanelib.palette_rgb42palette(wp)
        bitplanelib.palette_dump(wprgb,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("fade_palettes:\n")
    for sf in special_fade_palettes:
        bitplanelib.palette_dump(sf,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
        f.write("\n")

BLOCK_DISPLAY_MASK = 1<<14
DO_DISPLAY_MASK = 1

def gen_codes(i):
    im = (i<<1)
    return im | DO_DISPLAY_MASK,(0x800 + im) | DO_DISPLAY_MASK

gs_array = [0]*SPRITE_NB_TILES
for i in group_sprite_pairs:
    gs_array[i],gs_array[i+1] = gen_codes(i)

for i in group_sprite_triplets:
    gs_array[i],gs_array[i+2] = gen_codes(i)
    gs_array[i+1] = BLOCK_DISPLAY_MASK    # never display alone!
for i in group_sprite_quadruplets:
    gs_array[i],gs_array[i+3] = gen_codes(i)
    gs_array[i+1] = BLOCK_DISPLAY_MASK    # never display alone!
    gs_array[i+2] = BLOCK_DISPLAY_MASK    # never display alone!

with open(src_dir / "sprite_groups.68k","w") as f:
    f.write(generated_message)
    f.write("* see amiga.68k display_one_bob routine to know how this works\n")

    bitplanelib.dump_asm_bytes(gs_array,f,mit_format=True,size=2)


# merge both tables
fg_tile_table = [a if any(a) else b for a,b in zip(fg_tile_upper_table,fg_tile_lower_table)]

with open(src_dir / "graphics_aga.68k","w") as f:
    f.write(generated_message)
    f.write("\t.global\tfg_character_table\n")
    f.write("\t.global\tbob_table\n")

    f.write("fg_character_table:\n")

    dump_tile_layer(fg_tile_table,"fg")


    for k,v in tile_plane_cache.items():
        f.write(f"tile_plane_{v:02d}:")
        dump_asm_bytes(k,f)


    f.write("bob_table:\n")
    for i,tile_entry in enumerate(sprite_table):
        f.write("\t.long\t")
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            f.write(f"{prefix}_{i:02x}")
        else:
            f.write("0")
        f.write("\n")


    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            f.write(f"{prefix}_{i:02x}:\n")
            for j,t in enumerate(tile_entry):
                f.write("\t.long\t")
                if t:
                    f.write(f"{prefix}_{i:02x}_{j:02x}")
                else:
                    f.write("0")
                f.write("\n")


    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            for j,t in enumerate(tile_entry):
                if t:
                    name = f"{prefix}_{i:02x}_{j:02x}"

                    f.write(f"{name}:\n")
                    height = 0

                    offset = 0
                    for orientation,_ in plane_orientations:
                        if orientation in t:
                            width = t[orientation]["width"]
                            height = t[orientation]["height"]
                            offset = t[orientation]["y_start"]
                            break
                    else:
                        raise Exception(f"height not found for {name}!!")
                    for orientation,_ in plane_orientations:
                        if orientation == "standard":
                            f.write("* orientation={}\n".format(orientation))
                            active_planes = 0
                            bitplanes = t[orientation]["bitplanes"]

                            for j,bitplane_id in enumerate(bitplanes):
                                if bitplane_id:
                                    active_planes |= 1<<j

                            f.write(f"\t.word\t{height},{width},{offset},0x{active_planes:x}\n")
                            for bitplane_id in bitplanes:
                                f.write("\t.long\t")
                                if bitplane_id:
                                    f.write(f"bob_plane_{bitplane_id:02d}")
                                else:
                                    f.write("0")
                                f.write("\n")


    f.write("\t.section\t.datachip\n")

    for k,v in bob_plane_cache.items():
        f.write(f"\t.word\t0    | plane {v:02d} orientation\n")
        f.write(f"bob_plane_{v:02d}:")
        dump_asm_bytes(k,f)


