import pathlib,glob,json
import os,re
from shared import sheets_path,src_dir

nb_cols = 64
dct = {}

def encode_rgb(rgb):
    c = [int(i)>>4 for i in rgb.split(",")]  # rgb4
    return f"0x{c[0]:02x}{(c[1]<<4)+c[2]:02x}"

def doit():
    for p in sheets_path.glob("bg_tiles/*/palette0 colors_256.txt"):
        d = str(pathlib.Path(p).parent)
        with open(p) as f:
            f.readline()
            f.readline()
            f.readline()
            # keep only rgb
            colors = [",".join(next(f).strip().split(",")[:3]) for _ in range(nb_cols)]
        dct[d] = colors

    # look for 2 indexes of colors that define a particular palette
    # there are several possibilities, pick the first one

    for i in range(nb_cols):
        cols1 = {v[i] for k,v in dct.items()}
        if len(cols1)==len(dct):
            break
    else:
        raise Exception("Could not find unique color indexes")



    cols = {os.path.basename(k):{i:encode_rgb(v[i]) for i in range(nb_cols)} for k,v in dct.items()}
    with open("colors.json","w") as f:
        json.dump(cols,f,indent=2)


    # now dump the value
    with open(src_dir / "context.68k","w") as f:
        f.write("""* generated by find_different_colors.py
* if color index matches the encoded value (RGB4>>4)
* then it has to be the following context index, lookup name in the table
* note that level 1 and level 2 share the exact same palette
""")
        f.write("unique_color_index:\n")
        f.write(f"\t.word\t{i}\n")
        f.write("context_data:\n")

        ctxname = []
        for cci,(k,v) in enumerate(sorted(dct.items())):
            cname = pathlib.Path(k).name
            for a in [i]:
                f.write(f"\t.word\t{encode_rgb(v[a])}  | rgb for color {a}, context {cname}\n")
            ctxname.append((f"{cname}_path",str(cname)))
            f.write(f"\t.word\t{cci}  | context index\n")
        f.write("\t.word\t-1\n\n")

        f.write("context_name_table:\n")
        for c,_ in ctxname:
            f.write(f"\t.long\t{c}\n")
        f.write("\n")
        for c,cs in ctxname:
            f.write(f'{c}:\n\t.asciz\t"{cs}"\n')
        f.write("\t.align\t2\n")

if __name__ == "__main__":
    doit()