import pathlib,glob
import os,re
from shared import sheets_path,src_dir

nb_cols = 64
dct = {}

def encode_rgb(rgb):
    c = [int(i)>>4 for i in rgb.split(",")]  # rgb4
    return f"0x{((c[0]<<4)+c[1]):02x}{(c[2]<<4):02x}"

def doit():
    for p in sheets_path.glob("bg_tiles/*/palette0 colors_256.txt"):
        d = str(pathlib.Path(p).parent)
        with open(p) as f:
            f.readline()
            f.readline()
            f.readline()
            # keep only rgb
            colors = [",".join(next(f).strip().split(",")[:3]) for _ in range(nb_cols)]
        dct[d] = colors

    # look for 2 indexes of colors that define a particular palette
    # there are several possibilities, pick the first one
    ucf = False
    for i in range(nb_cols):
        cols1 = [v[i] for k,v in dct.items()]
        for j in range(nb_cols):
            cols2 = [v[j] for k,v in dct.items()]
            colmat = set(zip(cols1,cols2))
            if len(colmat)==len(dct):
                ucf = True
                break
        if ucf:
            break

    if not ucf:
        raise Exception("Could not find unique color indexes")

    # now dump the value
    with open(src_dir / "context.68k","w") as f:
        f.write("""* generated by find_different_colors.py
* if both color indexes match the encoded value (RGB4 0 padded like in the game)
* then it has to be the following context index, lookup name in the table
""")
        f.write("unique_color_indexes:\n")
        f.write(f"\t.word\t{i},{j}\n")
        f.write("context_data:\n")

        ctxname = []
        for cci,(k,v) in enumerate(sorted(dct.items())):
            cname = pathlib.Path(k).name
            for a in [i,j]:
                f.write(f"\t.word\t{encode_rgb(v[a])}  | rgb for color {a}, context {cname}\n")
            ctxname.append((f"{cname}_path",str(cname)))
            f.write(f"\t.word\t{cci}  | context index\n")
        f.write("\t.word\t-1\n\n")

        f.write("context_name_table:\n")
        for c,_ in ctxname:
            f.write(f"\t.long\t{c}\n")
        f.write("\n")
        for c,cs in ctxname:
            f.write(f'{c}:\n\t.asciz\t"{cs}"\n')
        f.write("\t.align\t2\n")

if __name__ == "__main__":
    doit()